apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-configapp-secret-files
  labels:
    app: {{ .Release.Name }}-configapp
type: Opaque
stringData:
  credentials.json: |
    {
      "username": "admin",
      "password": "{{ .Values.secrets.databasePassword }}",
      "api_key": "{{ .Values.secrets.apiKey }}"
    }
  
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    DEMO-PRIVATE-KEY-DO-NOT-USE-IN-PRODUCTION
    -----END PRIVATE KEY-----
