apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-configapp-secret
  labels:
    app: {{ .Release.Name }}-configapp
type: Opaque
stringData:
  database.password: {{ .Values.secrets.databasePassword | quote }}
  api.key: {{ .Values.secrets.apiKey | quote }}
  jwt.secret: {{ .Values.secrets.jwtSecret | quote }}
