environment: development

replicaCount: 1

config:
  logLevel: debug
  debugMode: true
  maxConnections: 50

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
