apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webservice-clusterip
  labels:
    app: {{ .Release.Name }}-webservice
    type: clusterip
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-webservice
