{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rbacapp
  labels:
    app: {{ .Release.Name }}-rbacapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-rbacapp
subjects:
- kind: ServiceAccount
  name: {{ include "rbacapp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
