{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-condapp
  labels:
    app: {{ .Release.Name }}-condapp
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.monitoring.enabled }}
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    app: {{ .Release.Name }}-condapp
{{- end }}
